[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s

# max length of characters in migration script filename
# move to 256 for Windows.
truncate_slug_length = 64

# set to 'preview' or 'prod' for specific snippet imports
sqlalchemy.url = driver://username:password@host:port/database

# revision identification information
revision_environment = false
# sourceless = false

# version locations
version_locations = %(here)s/versions

# version path separator
version_path_separator = os



[post_write_hooks]
# hooks for post-writing migration files
# format the file with Black
hooks = black
black.type = console_scripts
black.entrypoint = black
# black.options = -l 88

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
